---
- name: Restart a container
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: redmine
    image: "redmine:{{ redmine_version }}"
    state: started
    ports:
     - "{{ redmine_port }}:3000"
    env:
      REDMINE_DB_POSTGRES: '{{ db_host }}'
      REDMINE_DB_USERNAME: '{{ db_username }}'
      REDMINE_DB_PASSWORD: '{{ db_password }}'
      REDMINE_DB_PORT: '{{ db_port }}'
      REDMINE_DB_DATABASE: '{{ db_name }}'
  tags:
  - containers
  - redmine-server
  - config
...